### PR TITLE
Anvil & Grindstone support for custom enchantments

### PR DESCRIPTION
**Pull request by Boy0000**

### CODE REVIEW

**Comment by Boy0000** [comment]
Lore is still not removed correctly.
If you upgrade from [insert enchantment] level 1 -> 2 it adds another line.
So removing needs to remove every line containing "enchantmentname"

**Comment by Boy0000** [comment]
@0ffz look over?

**Comment by 0ffz** [comment]
Ive started going over this and it feels like very java-ey boilerplate around everything. If we're gonna go through all this bulk, I'd like to go all in on it with Geary, basically think about how enchantments would look like as entities and make it sync with Minecraft. It's a bit harder of a project but definitely something worth pursuing if you wanna get accustomed to ECS.

**Comment by Boy0000** [comment]
Not sure what you mean. The enchantments are currently registered as enchantments like any other.
But since enchants displayed by client, it doesnt show the custom ones. Hence lore
Most of this is also just because lore isnt applied otherwise.

So not entirely sure what moving this and reworking everything would really do?

**Pull request closed without merging**
